<a href="https://colab.research.google.com/github/sahithi-streamer/python-basics/blob/main/(minor%20project)_Image_classification_MAY_batch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#IMAGE CLASSIFICATION-Data in images
#Using Python libraries for scraping the images from bing
!pip install bing-image-downloader 


In [4]:
# Creating a directory named images
!mkdir images                      


In [5]:
# Step-1: Gathering the data of images.
## Download images from bing to the directory
from bing_image_downloader import downloader
downloader.download("cheetah",limit=30,output_dir='images', adult_filter_off=True)

[%] Downloading Images to /content/images/cheetah


[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://worldwideexperience.com/wp-content/uploads/2019/10/cheetah.jpg
[%] File Downloaded !

[%] Downloading Image #2 from http://1.bp.blogspot.com/-s3rKgPpsrq8/Tvx_HDljtdI/AAAAAAAAEDY/dOcQxz75hI0/s1600/cheetahs_1646474i4.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://willwork4travel.com/wp-content/uploads/2012/05/P1050154.jpg
[%] File Downloaded !

[%] Downloading Image #4 from http://1.bp.blogspot.com/-Lqv46GHcn0k/UKNcFWZvGII/AAAAAAAAADU/022KqyaSPnM/s1600/cheetahs+pride.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://www.rd.com/wp-content/uploads/2019/11/shutterstock_762734848.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://1.bp.blogspot.com/-xroPGO7XnEA/TVbIMY3jQDI/AAAAAAAAAAs/3UbiHKOG4ec/s1600/DSCN2773.JPG
[%] File Downloaded !

[%] Downloading Image #7 from http://www.cbc.ca/kidscbc2/content/t

In [6]:
downloader.download("dog",limit=30,output_dir='images',adult_filter_off=True)

[%] Downloading Images to /content/images/dog


[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://cdn.newsapi.com.au/image/v1/098fe707e818d4d04deb0e27af7186bd?width=650
[%] File Downloaded !

[%] Downloading Image #2 from http://schoolmum.net/wp-content/uploads/2016/12/RedDog-TrueBlue-FULL.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://i.ytimg.com/vi/Pc1ms7EG7UE/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://static.ffx.io/images/$width_620%2C$height_414/t_crop_fill/q_86%2Cf_auto/t_theage_no_label_social_wm/l_text:PT Sans_41_bold_italic: from %2Cg_south_west%2Cy_84%2Cx_384%2Cco_rgb:0a1633/l_text:PT Sans_41_bold:  %2Cg_south_west%2Cy_90%2Cx_471%2Cco_rgb:0a1633/l_text:AbrilTitling-Bold.ttf_83: 2012 %2Cg_south_west%2Cy_15%2Cx_370%2Cco_rgb:0a1633/c948ee51fe003a1416ba1fd5de5d5fcf23452d74
[!] Issue getting: https://static.ffx.io/images/$width_620%2C$height_414/t_crop_fill/q_86%2Cf_auto/t_theage_no_l

In [18]:
# Step-2: Preprocessing: 1. Resize the images(pixels)
#                2. Flatten (matrices to vector conversion)

import os
import numpy as np
import matplotlib.pyplot as plt
#Scikit-image library for resizing and reading
from skimage.transform import resize
from skimage.io import imread

images = []
flatten_data = []
target = []
CATEGORIES = ['cheetah','dog']
# For Considering the path
data_dir = '/content/images'

# Now start iterating

for i in CATEGORIES: # where i=category
  # we are label encoding the values
  num_class = CATEGORIES.index(i)
  # Creating the respective paths to the images for usage
  path = os.path.join(data_dir,i) 
  for img in os.listdir(path):
     imgs_array = imread(os.path.join(path,img))
    # Normalizes the value from 0 to 1
     img_resized = resize(imgs_array,(150,150,3)) 
     flatten_data.append(img_resized.flatten())
     images.append(img_resized)
     target.append( num_class)

flatten_data = np.array(flatten_data)
target = np.array(target)
images = np.array(images)


In [21]:
print(flatten_data[1]) # just checking the data we got
print(target[0])
print(images[1])

[0.03529412 0.         0.         ... 0.04705882 0.00392157 0.        ]
0
[[[0.03529412 0.         0.        ]
  [0.0372549  0.         0.        ]
  [0.03921569 0.         0.        ]
  ...
  [0.03921569 0.         0.        ]
  [0.03921569 0.         0.        ]
  [0.03529412 0.         0.        ]]

 [[0.03921569 0.         0.        ]
  [0.03921569 0.         0.        ]
  [0.03921569 0.         0.        ]
  ...
  [0.03921569 0.         0.        ]
  [0.03921569 0.         0.        ]
  [0.03921569 0.         0.        ]]

 [[0.03921569 0.         0.        ]
  [0.04313725 0.         0.        ]
  [0.04281046 0.         0.        ]
  ...
  [0.03921569 0.         0.        ]
  [0.03431373 0.         0.        ]
  [0.03921569 0.         0.        ]]

 ...

 [[0.04313725 0.         0.        ]
  [0.04313725 0.         0.        ]
  [0.05163399 0.00849673 0.00849673]
  ...
  [0.04705882 0.         0.        ]
  [0.04607843 0.         0.        ]
  [0.04705882 0.00588235 0.        ]]



In [23]:
# Step-3: Splitting the data into  Testing ,Training.
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(flatten_data,target,test_size=0.3,random_state=107)

In [24]:
#Using SVM algorithm for classification
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid = [{'C':[1,10,100,1000],'kernel':['linear']},{'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']}]
# Here make sure the probability is true for getting all the probabilities in output
svc = svm.SVC(probability=True)
clf = GridSearchCV(svc,param_grid)
clf.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [25]:
y_test

array([1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1])

In [26]:
y_pred = clf.predict(x_test)
y_pred

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0])

In [29]:
# Evaluation: checking the accuracy of the model
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_pred,y_test)

0.6111111111111112

In [40]:
# Save the model using Pickle library
import pickle
pickle.dump(clf,open('img_model.p','wb'))

In [41]:
model = pickle.load(open('img_model.p','rb'))

In [44]:
# Step-3: Deployment : using streamlit-webapp
!pip install streamlit --quiet
!pip install pyngrok==4.1.1 --quiet
from pyngrok import ngrok

     |████████████████████████████████| 7.8MB 7.2MB/s 
     |████████████████████████████████| 112kB 61.4MB/s 
     |████████████████████████████████| 174kB 54.7MB/s 
     |████████████████████████████████| 81kB 11.3MB/s 
     |████████████████████████████████| 4.2MB 45.7MB/s 
     |████████████████████████████████| 71kB 10.7MB/s 
     |████████████████████████████████| 122kB 53.8MB/s 
ERROR: google-colab 1.0.0 has requirement ipykernel~=4.10, but you'll have ipykernel 5.5.5 which is incompatible.


In [48]:
%%writefile app.py
import streamlit as st
import numpy as np
from skimage.io import imread
from skimage.transform import resize
import pickle 
from PIL import Image
st.set_option('deprecation.showfileUploaderEncoding', False)
st.title('Image Classifier using Machine Learning')
st.text('Upload the Respective-Image')

model = pickle.load(open('img_model.p','rb'))

uploaded_file = st.file_uploader("Choose an image for output...", type="jpg")
if uploaded_file is not None:
  img = Image.open(uploaded_file)
  st.image(img,caption='Uploaded Image')

  if st.button('PREDICT THE OUTPUT'):
    CATEGORIES = ['cheetah','dog']
    st.write('Result is >>...')
    flatten_data=[]
    img = np.array(img)
    img_resized = resize(img,(150,150,3))
    flatten_data.append(img_resized.flatten())
    flatten_data = np.array(flatten_data)
    y_out = model.predict(flatten_data)
    y_out = CATEGORIES[y_out[0]]
    st.title(f' PREDICTED OUTPUT: {y_out}')
    q = model.predict_proba(flatten_data)
    for index, item in enumerate(CATEGORIES):
      st.write(f'{item} : {q[0][index]*100}%')



Overwriting app.py


In [46]:
!nohup streamlit run app.py &

url = ngrok.connect(port='8501')
url

nohup: appending output to 'nohup.out'


'http://7b29834be067.ngrok.io'